"""
Stock Portfolio Tracker
Developed by: Elias Zananiri
Date: June 2026

Description: A simple stock tracker that calculates total investment value
based on user inputs and hardcoded stock prices.
"""

# Hardcoded stock prices dictionary
STOCK_PRICES = {
    "AAPL": 180.00,
    "TSLA": 250.00,
    "GOOGL": 140.00,
    "AMZN": 130.00,
    "MSFT": 330.00,
    "META": 310.00,
    "NFLX": 450.00,
    "NVDA": 120.00
}

def display_available_stocks():
    """Display all available stocks with their prices."""
    print("\n" + "="*50)
    print("AVAILABLE STOCKS & PRICES:")
    print("="*50)
    for symbol, price in STOCK_PRICES.items():
        print(f"  {symbol}: ${price:.2f}")
    print("="*50 + "\n")

def get_user_portfolio():
    """Get stock names and quantities from user input."""
    portfolio = []
    
    print("\n" + "="*50)
    print("STOCK PORTFOLIO TRACKER")
    print("Developed by: Elias Zananiri")
    print("="*50)
    
    display_available_stocks()
    
    num_stocks = int(input("How many different stocks do you want to add? "))
    
    for i in range(num_stocks):
        print(f"\n--- Stock #{i+1} ---")
        symbol = input("Enter stock symbol: ").upper().strip()
        
        # Validate if stock exists in our price dictionary
        while symbol not in STOCK_PRICES:
            print(f"'{symbol}' not found. Available stocks: {', '.join(STOCK_PRICES.keys())}")
            symbol = input("Enter a valid stock symbol: ").upper().strip()
        
        quantity = int(input(f"Enter quantity of {symbol}: "))
        
        portfolio.append({
            'symbol': symbol,
            'quantity': quantity,
            'price': STOCK_PRICES[symbol]
        })
    
    return portfolio

def calculate_total_investment(portfolio):
    """Calculate total investment value."""
    total = 0
    print("\n" + "="*50)
    print("PORTFOLIO SUMMARY")
    print("="*50)
    print(f"{'Symbol':<10} {'Quantity':<10} {'Price':<10} {'Value':<15}")
    print("-"*45)
    
    for stock in portfolio:
        value = stock['quantity'] * stock['price']
        total += value
        print(f"{stock['symbol']:<10} {stock['quantity']:<10} ${stock['price']:<9.2f} ${value:<14.2f}")
    
    print("-"*45)
    print(f"{'TOTAL INVESTMENT:':<40} ${total:.2f}")
    print("="*50)
    
    return total

def save_to_file(portfolio, total, filename="portfolio_report.txt"):
    """Save portfolio report to a file."""
    try:
        with open(filename, 'w') as file:
            file.write("="*60 + "\n")
            file.write("STOCK PORTFOLIO TRACKER REPORT\n")
            file.write(f"Generated by: Elias Zananiri\n")
            file.write("="*60 + "\n\n")
            
            file.write(f"{'Symbol':<10} {'Quantity':<10} {'Price ($)':<12} {'Value ($)':<15}\n")
            file.write("-"*50 + "\n")
            
            for stock in portfolio:
                value = stock['quantity'] * stock['price']
                file.write(f"{stock['symbol']:<10} {stock['quantity']:<10} ${stock['price']:<11.2f} ${value:<14.2f}\n")
            
            file.write("-"*50 + "\n")
            file.write(f"{'TOTAL INVESTMENT:':<40} ${total:.2f}\n\n")
            file.write("="*60 + "\n")
            file.write("End of Report\n")
        
        print(f"\n✓ Report successfully saved to '{filename}'")
        return True
    except Exception as e:
        print(f"\n✗ Error saving file: {e}")
        return False

def save_to_csv(portfolio, total, filename="portfolio_report.csv"):
    """Save portfolio report to a CSV file."""
    try:
        with open(filename, 'w') as file:
            file.write("Symbol,Quantity,Price ($),Value ($)\n")
            
            for stock in portfolio:
                value = stock['quantity'] * stock['price']
                file.write(f"{stock['symbol']},{stock['quantity']},{stock['price']:.2f},{value:.2f}\n")
            
            file.write(f"\nTotal Investment,{total:.2f}\n")
        
        print(f"\n✓ CSV report successfully saved to '{filename}'")
        return True
    except Exception as e:
        print(f"\n✗ Error saving CSV file: {e}")
        return False

def main():
    """Main function to run the Stock Portfolio Tracker."""
    print("\n" + "="*50)
    print("  WELCOME TO STOCK PORTFOLIO TRACKER")
    print("  Developed by Elias Zananiri")
    print("="*50)
    
    while True:
        print("\n--- MAIN MENU ---")
        print("1. Create/Edit Portfolio")
        print("2. Calculate Total Investment")
        print("3. Save Report to TXT file")
        print("4. Save Report to CSV file")
        print("5. Exit")
        
        choice = input("\nEnter your choice (1-5): ").strip()
        
        if choice == '1':
            portfolio = get_user_portfolio()
            print("\n✓ Portfolio created successfully!")
        elif choice == '2':
            if 'portfolio' in locals() and portfolio:
                total = calculate_total_investment(portfolio)
            else:
                print("\n⚠ Please create a portfolio first (Option 1)")
        elif choice == '3':
            if 'portfolio' in locals() and portfolio:
                if 'total' not in locals():
                    total = calculate_total_investment(portfolio)
                save_to_file(portfolio, total)
            else:
                print("\n⚠ Please create a portfolio first (Option 1)")
        elif choice == '4':
            if 'portfolio' in locals() and portfolio:
                if 'total' not in locals():
                    total = calculate_total_investment(portfolio)
                save_to_csv(portfolio, total)
            else:
                print("\n⚠ Please create a portfolio first (Option 1)")
        elif choice == '5':
            print("\n" + "="*50)
            print("Thank you for using Stock Portfolio Tracker!")
            print("Developed by Elias Zananiri")
            print("="*50 + "\n")
            break
        else:
            print("\n⚠ Invalid choice. Please enter 1-5")

# Run the program
if __name__ == "__main__":
    main()
